# Enable the nice!view display.
CONFIG_ZMK_DISPLAY=y

# Keep the memory display visible while the keyboard is idle.
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n

# Normal nice!view colors:
# white background + black foreground/details.
CONFIG_NICE_VIEW_WIDGET_INVERTED=n

# Give the custom display worker enough stack for the three canvas blocks.
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=4096
